# Generated by Django 4.0.4 on 2022-04-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='nesting',
            new_name='level',
        ),
    ]
